dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: decide-practica-7
  strategy: git
  api_key:
    secure: I0tHwzqIa5OvXU+zi3ff34B1YRbC+XpDwquIeH3we+tvbW1N0gZP6hLc3KbBKRTcR9cQfrfzcUmMHA2VF1o5IpuZWfMFKp9Po0WU7o/SVQ1Q/HgGQ1fEhNNvaHy5weWI5IAJTFKkQPV/uBd5NhHYB/Bl+rBfykevQeWNoI51SH9LChmaS2ocM54jqsZ3BZy1MJ7YApaCnZoT5ECaFwNWf0IaHg5gZVebnvjVVs/kJeHXEJeZs2LfDNrdqJvvOmtShAJrw5VjUGiOjIJ1FXEayF8/ramAPpEbe8R2VAcU2BvDPPoSzJ8vi9nUQfT314TSfsXOpv5ukDJIRudeLy8eP5pkRqQTdgAMnt5V1NtyF4UyCSq5ZsjCmLBDCyEN/NPRx0j1FVKAsmy9S7iPSrMDhVZEWWoQU/HM8TKDKmnqJdYWIcQiXcTF1mae2P+qRsh6OXol4nx6B3VCF/ZBuyRopCG8qlZTtiIJBAsffkpWzMbnJi/XBh2F8ZKQQJfQo2Vn0z60Ce0L00Y3ttinLLN2ny79bG+TVWrcolWXjoHJ4Fxb40QYSJudz7j2+P1BwN94Q4jNMIIMvKe5RRO9zMBGlqw95tc+XAlpXrPDtTpig/8g7oTgAMdpg6a4uHBhLS1BqA1bVa3baiZOoRuaR3swbtai7iJYh7+qqNm8tdiP4aM=
